### ISSUE TITLE
Connecting to rest service failed

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-admin#30] opened 2018-06-10 14:14 UTC
Hi,

I tried to connect to the rest-service over the imixs-admin console and get the following error in the logs:
`16:02:30,541 WARN  [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-18) RESTEASY002142: Multiple resource methods match request "GET /documents/configuration". Selecting one. Matching methods: [public org.imixs.workflow.xml.XMLDataCollection org.imixs.workflow.jaxrs.DocumentRestService.getDocument(java.lang.String,java.lang.String), public org.imixs.workflow.xml.XMLDataCollection org.imixs.workflow.jaxrs.DocumentRestService.getConfiguration() throws java.lang.Exception]`

How can I solve this issue?

**Comment by rsoika** [comment] 2018-06-10 14:40
Please check your deployment artifact.  It sounds like there are two versions of imixs-jax-rs included. 
We also updated the Rest-API a little bit in the last releases. So it is recommended to use the latest build of Imixs-Admin Client. Also make sure your browser cache is cleared. This is because the admin-client is based on java script and there is also a new java script library included. But the error message sounds more that there are two version deployed. Note: wildfly and glassfish are both caching deployed aretefacts.

**Comment by chrisw14** [comment] 2018-06-10 16:16
Thank you! I solved it by updating imixs-admin.

**Comment by chrisw14** [comment] 2018-06-11 18:49
Okay, it seems that it doesn't solve the problem.

The two methods
public org.imixs.workflow.xml.XMLDataCollection org.imixs.workflow.jaxrs.DocumentRestService.getDocument(java.lang.String,java.lang.String)
public org.imixs.workflow.xml.XMLDataCollection org.imixs.workflow.jaxrs.DocumentRestService.getConfiguration() throws java.lang.Exception

I thinks it's because the following path can match both:
	@Path("/{uniqueid}")
	@Path("/configuration")

See https://stackoverflow.com/questions/46081787/resteasy002142-multiple-resource-methods-match-request

So I can't rebuild the index over the imixs-admin...

**Comment by rsoika** [comment] 2018-06-11 21:03
This is interesting.... I did not run into this problem and I use the version in Wildfly (RestEasy) and also in Glassfish/Payara (Jersey). 
But it is true, the path is not unique after all.

**Comment by rsoika** [comment] 2018-06-11 21:07
I opened a new bug report:
https://github.com/imixs/imixs-workflow/issues/390

**Comment by rsoika** [comment] 2018-06-11 21:11
As we have this non-unique path pattern since several versions, please try to undeploy your application completely and restart your wildfly server. After that deploy your new version once again. I guess this will work. But of course we need to find a solution.

**Comment by chrisw14** [comment] 2018-06-12 18:05
Okay, I tried it again and it doesn't work for me :-(
The log always appears when I connect to the rest service on the "Home" link in imixs-admin.

**Comment by rsoika** [comment] 2018-06-12 20:05
We need to change the rest api and also the admin client code for this. 
Which version of Wildfly are you using?

**Comment by chrisw14** [comment] 2018-06-12 20:15
The product version is 10.1.0.Final

**Comment by rsoika** [comment] 2018-06-12 20:35
Just to make it more clear for me. You problem is the warning message in the log file - right?
But you can still work with the admin client? Means - you can see the index list if you click on 'configuration'

![image](https://user-images.githubusercontent.com/1339124/41315808-eac8ccb4-6e90-11e8-9caa-64e4e02f839d.png)

**Comment by rsoika** [comment] 2018-06-12 21:06
I think the problem is now fixed in the master branch by adding a regex. 
See issue https://github.com/imixs/imixs-workflow/issues/390

Thanks for your finding!

**Closed** 2018-09-28 22:58 UTC
Labels: Testing, bug, question
